
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class PemesananTiketKapal extends javax.swing.JFrame {
    
    int batam, jakarta, lampung, sabang, beli, harga, total, bayar, kembali;
    DefaultTableModel model;

    /**
     * Creates new form PemesananTiketKapal
     */
    public PemesananTiketKapal() {
        initComponents();
        this.setLocationRelativeTo(null);//make center
        String []judul={"Nomor Kapal","Nomor Deck","Nama Penumpang","Tujuan Pelayaran","Harga Tiket","Jumlah Tiket","Total Bayar","Uang Bayar","Uang Kembali"};
        model = new DefaultTableModel(judul,0);
        jTable1.setModel(model);
        tampilkan();
    }
    
    private void tampilkan(){
        
        int row = jTable1.getRowCount();
        for(int a=0;a<row;a++){
            model.removeRow(0);
        }
        try{
        Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/tiket","root","");
        ResultSet rs = cn.createStatement().executeQuery("select * from tiket_kapal");
        while(rs.next()){
            String data[]={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)};
            model.addRow(data);
        }
      } catch (SQLException ex) {
          Logger.getLogger(PemesananTiketKapal.class.getName()).log(Level.SEVERE, null, ex);
    }
   }
    
    private void reset(){
        nokapal_txt.setText("");
        nodeck_txt.setText("");
        nama_txt.setText("");
        tujuan.setSelectedItem("~Pilih Tujuan~");
        harga_txt.setText("");
        jumlah_txt.setText("");
        uangbayar_txt.setText("");
        uangkembali_txt.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nokapal_txt = new javax.swing.JTextField();
        nama_txt = new javax.swing.JTextField();
        tujuan = new javax.swing.JComboBox<>();
        harga_txt = new javax.swing.JTextField();
        jumlah_txt = new javax.swing.JTextField();
        totalbayar_txt = new javax.swing.JTextField();
        uangbayar_txt = new javax.swing.JTextField();
        uangkembali_txt = new javax.swing.JTextField();
        btn_hitung = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        nodeck_txt = new javax.swing.JTextField();
        btn_input = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("No. Kapal");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nama Penumpang");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Tujuan Pelayaran");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Harga Tiket");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Jumlah Tiket");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Total Bayar");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Uang Bayar");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Uang Kembali");

        tujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~Pilih Tujuan~", "Batam", "Jakarta", "Lampung", "Sabang" }));
        tujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuanActionPerformed(evt);
            }
        });

        harga_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga_txtActionPerformed(evt);
            }
        });

        jumlah_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_txtActionPerformed(evt);
            }
        });
        jumlah_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jumlah_txtKeyReleased(evt);
            }
        });

        uangbayar_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uangbayar_txtActionPerformed(evt);
            }
        });

        uangkembali_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uangkembali_txtActionPerformed(evt);
            }
        });

        btn_hitung.setText("Hitung");
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("No. Deck");

        btn_input.setBackground(new java.awt.Color(0, 151, 230));
        btn_input.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_input.setText("Input");
        btn_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(41, 128, 185));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Pemesanan Tiket Kapal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_update.setBackground(new java.awt.Color(0, 151, 230));
        btn_update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(194, 54, 22));
        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(nokapal_txt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nama_txt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tujuan, javax.swing.GroupLayout.Alignment.LEADING, 0, 263, Short.MAX_VALUE)
                        .addComponent(harga_txt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jumlah_txt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(totalbayar_txt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(uangbayar_txt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(uangkembali_txt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(77, 77, 77)
                            .addComponent(btn_hitung))
                        .addComponent(nodeck_txt, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_input)
                        .addGap(26, 26, 26)
                        .addComponent(btn_update)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nokapal_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nodeck_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nama_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(harga_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jumlah_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(totalbayar_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(uangbayar_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_hitung)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uangkembali_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_input)
                    .addComponent(btn_update)
                    .addComponent(btn_delete))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nomor Kapal", "Nomor Deck", "Nama Penumpang", "Tujuan Pelayaran", "Harga Tiket", "Jumlah Tiket", "Total Bayar", "Uang Bayar", "Uang Kembali"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btn_keluar.setBackground(new java.awt.Color(194, 54, 22));
        btn_keluar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_keluar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_keluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uangkembali_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uangkembali_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uangkembali_txtActionPerformed

    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungActionPerformed
        // TODO add your handling code here:
        int total=Integer.parseInt(totalbayar_txt.getText());
        int uang=Integer.parseInt(uangbayar_txt.getText());
        int hasil=uang-total;
        uangkembali_txt.setText(Integer.toString(hasil));
    }//GEN-LAST:event_btn_hitungActionPerformed

    private void tujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuanActionPerformed
        // TODO add your handling code here:
        if(tujuan.getSelectedItem().equals("Pilih Tujuan")){
            buttonGroup1.clearSelection();
            harga_txt.setText("");
        }
        else if(tujuan.getSelectedItem().equals("Batam")){
            harga_txt.setText("300000");
        }
        else if(tujuan.getSelectedItem().equals("Jakarta")){
            harga_txt.setText("1500000");
        }
        else if(tujuan.getSelectedItem().equals("Lampung")){
            harga_txt.setText("1000000");
        }
        else if(tujuan.getSelectedItem().equals("Sabang")){
            harga_txt.setText("250000");
        }
    }//GEN-LAST:event_tujuanActionPerformed

    private void harga_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harga_txtActionPerformed

    private void jumlah_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_txtActionPerformed
        // TODO add your handling code here:
        beli=Integer.parseInt(jumlah_txt.getText());
        harga=Integer.parseInt(harga_txt.getText());
        total=bayar*harga;
        totalbayar_txt.setText(String.valueOf(total));
    }//GEN-LAST:event_jumlah_txtActionPerformed

    private void jumlah_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlah_txtKeyReleased
        // TODO add your handling code here:
        int a, b, c;
        a=Integer.valueOf(harga_txt.getText());
        b=Integer.valueOf(jumlah_txt.getText());
        c=a*b;
        totalbayar_txt.setText(""+c);
    }//GEN-LAST:event_jumlah_txtKeyReleased

    private void uangbayar_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uangbayar_txtActionPerformed
        // TODO add your handling code here:
        bayar=Integer.parseInt(uangbayar_txt.getText());
        kembali=Integer.parseInt(totalbayar_txt.getText());
        total=bayar-kembali;
        uangkembali_txt.setText(String.valueOf(total));
    }//GEN-LAST:event_uangbayar_txtActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this,
                "Konfirmasi Keluar Aplikasi",
                "Yakin untuk keluar dari program",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            MenuPilihanTiket Menu;
            Menu = new MenuPilihanTiket();
            Menu.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/tiket","root","");
            cn.createStatement().executeUpdate("insert into tiket_kapal values"+"('"+nokapal_txt.getText()+"','"+nodeck_txt.getText()+"','"+nama_txt.getText()+"','"+tujuan.getSelectedItem()+"','"+harga_txt.getText()+"','"+jumlah_txt.getText()+"','"+totalbayar_txt.getText()+"','"+uangbayar_txt.getText()+"','"+uangkembali_txt.getText()+"')");
            tampilkan();
            reset();
            
            buttonGroup1.clearSelection();
            nokapal_txt.setText("");
            nodeck_txt.setText("");
            nama_txt.setText("");
            tujuan.setSelectedItem("~Pilih Tujuan~");
            harga_txt.setText("");
            jumlah_txt.setText("");
            uangbayar_txt.setText("");
            uangkembali_txt.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(PemesananTiketKapal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_inputActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        if(i>-1){
            nokapal_txt.setText(model.getValueAt(i, 0).toString());
            nodeck_txt.setText(model.getValueAt(i, 1).toString());
            nama_txt.setText(model.getValueAt(i, 2).toString());
            tujuan.setSelectedItem(model.getValueAt(i, 3).toString());
            harga_txt.setText(model.getValueAt(i, 4).toString());
            jumlah_txt.setText(model.getValueAt(i, 5).toString());
            uangbayar_txt.setText(model.getValueAt(i, 6).toString());
            uangkembali_txt.setText(model.getValueAt(i, 7).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/tiket","root","");
            cn.createStatement().executeUpdate("delete from tiket_kapal where no_kapal='"+nokapal_txt.getText()+"'");
            tampilkan();
            reset();
        } catch (SQLException ex) {
            Logger.getLogger(PemesananTiketKapal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE tiket_kapal SET no_kapal='"+nokapal_txt.getText()+"',no_deck='"+nodeck_txt.getText()+"', nama_penumpang='"+nama_txt.getText()+"',tujuan_pelayar='"+tujuan.getSelectedItem()+"',harga_tiket='"+harga_txt.getText()+"',jumlah_tiket='"+jumlah_txt.getText()+"',harga_total='"+totalbayar_txt.getText()+"',uang_bayar='"+uangbayar_txt.getText()+"',uang_bayar='"+uangbayar_txt.getText()+"',uang_kembali='"+uangkembali_txt.getText()+"'where no_kapal='"+nokapal_txt.getText()+"'";
            java.sql.Connection conn=(Connection)MyConnection.getConnection();
            java.sql.PreparedStatement pst =conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data berhasil di edit");
        }catch (SQLException e){
        JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
        new PemesananTiketKapal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PemesananTiketKapal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PemesananTiketKapal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PemesananTiketKapal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PemesananTiketKapal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PemesananTiketKapal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_hitung;
    private javax.swing.JButton btn_input;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField harga_txt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jumlah_txt;
    private javax.swing.JTextField nama_txt;
    private javax.swing.JTextField nodeck_txt;
    private javax.swing.JTextField nokapal_txt;
    private javax.swing.JTextField totalbayar_txt;
    private javax.swing.JComboBox<String> tujuan;
    private javax.swing.JTextField uangbayar_txt;
    private javax.swing.JTextField uangkembali_txt;
    // End of variables declaration//GEN-END:variables
}
